name: quote_buffer
description:
  Simplifies adding strings whose content is delimited by escaped quotation marks
  to Dart's string buffer.


version: 0.0.5
homepage: https://github.com/simphotonics/quote_buffer

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  generic_enum: ^0.0.6

dev_dependencies:
  test: ^1.11.0
