name: quote_buffer
description:
  Simplifies adding strings whose content is delimited by escaped quotation marks
  to Dart's string buffer.


version: 0.1.3
homepage: https://github.com/simphotonics/quote_buffer

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:

dev_dependencies:
  test: ^1.14.6
